# Files and directories
music_directory "/mnt/Content/Music/Complete songs/"
playlist_directory  "~/.config/mpd/playlists"
db_file             "~/.config/mpd/mpd.db"
log_file            "~/.config/mpd/mpd.log"
pid_file            "~/.config/mpd/mpd.pid"
state_file          "~/.confic/mpd/mpdstate"

# General music daemon options 
bind_to_address "localhost"
port "6600"
restore_paused "yes"
metadata_to_use "artist,album,title,name,genre"
auto_update "yes"
auto_update_depth "3"

# Symbolic link behavior
follow_outside_symlinks	"yes"
follow_inside_symlinks		"yes"

# Audio Output
audio_output {
	type "pipewire"
	name "PipeWire Output"
	mixer_type "software"
}